package com.example.lab1.mybatis.dao;

import com.example.lab1.mybatis.model.Sport;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface SportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SPORT
     *
     * @mbg.generated Tue Apr 05 18:19:25 EEST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SPORT
     *
     * @mbg.generated Tue Apr 05 18:19:25 EEST 2022
     */
    int insert(Sport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SPORT
     *
     * @mbg.generated Tue Apr 05 18:19:25 EEST 2022
     */
    Sport selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SPORT
     *
     * @mbg.generated Tue Apr 05 18:19:25 EEST 2022
     */
    List<Sport> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SPORT
     *
     * @mbg.generated Tue Apr 05 18:19:25 EEST 2022
     */
    int updateByPrimaryKey(Sport record);
}