package com.example.lab1.mybatis.dao;

import com.example.lab1.mybatis.model.University;
import org.mybatis.cdi.Mapper;

import java.util.List;
@Mapper
public interface UniversityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.UNIVERSITY
     *
     * @mbg.generated Tue Apr 05 18:19:25 EEST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.UNIVERSITY
     *
     * @mbg.generated Tue Apr 05 18:19:25 EEST 2022
     */
    int insert(University record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.UNIVERSITY
     *
     * @mbg.generated Tue Apr 05 18:19:25 EEST 2022
     */
    University selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.UNIVERSITY
     *
     * @mbg.generated Tue Apr 05 18:19:25 EEST 2022
     */
    List<University> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.UNIVERSITY
     *
     * @mbg.generated Tue Apr 05 18:19:25 EEST 2022
     */
    int updateByPrimaryKey(University record);
}