package com.example.lab1.mybatis.model;

public class Sport {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SPORT.ID
     *
     * @mbg.generated Tue Apr 05 18:19:25 EEST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SPORT.NAME
     *
     * @mbg.generated Tue Apr 05 18:19:25 EEST 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SPORT.ID
     *
     * @return the value of PUBLIC.SPORT.ID
     *
     * @mbg.generated Tue Apr 05 18:19:25 EEST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SPORT.ID
     *
     * @param id the value for PUBLIC.SPORT.ID
     *
     * @mbg.generated Tue Apr 05 18:19:25 EEST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SPORT.NAME
     *
     * @return the value of PUBLIC.SPORT.NAME
     *
     * @mbg.generated Tue Apr 05 18:19:25 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SPORT.NAME
     *
     * @param name the value for PUBLIC.SPORT.NAME
     *
     * @mbg.generated Tue Apr 05 18:19:25 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }
}